### ISSUE TITLE
Sounds files are not working

### ISSUE THREAD

**Issue by theextraordinary** [drogue-iot/hey-rodney#1]
the start.wav and end.wav files are not working

**Comment by ctron** [comment]
I am not sure what you mean by that?

**Comment by theextraordinary** [comment]
Sounds files uploaded there aren’t working Sent from Mail for Windows 10 From: Jens ReimannSent: 22 January 2021 18:51To: drogue-iot/hey-rodneyCc: Tony Stark; AuthorSubject: Re: [drogue-iot/hey-rodney] Sounds files are not working (#1) I am not sure what you mean by that?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
